fn main() {
    panic!("crash and burn");

    // The unrecoverable error is invoked using the panic! macro.

    // however it can also be caused by a bug in our program.
}
